verbose: false
checkUpdates: true
usePermissionsWhitelist: false
whitelistMessage: true
lockpair: true
lockedChestsSuck: false
suckRange: 3
suckInterval: 100
suckEffect: true
useWorldGuard: false
preventExplosions: true
useProtectiveAuras: false
key: 280
keyDurability: 0
comboKey: 352
comboKeyDurability: 0
useKeyDurability: false
consumeKey: false
openMessage: true
useLimits: false
lockLimits:
    example: 10
    anotherexample: 20
lockables:
    lockable:
        - CHEST
        - DISPENSER
        - JUKEBOX
        - ENCHANTMENT_TABLE
        - BREWING_STAND
        - WORKBENCH
        - FURNACE
        - BURNING_FURNACE
        - LEVER
        - STONE_BUTTON
        - TRAP_DOOR
        - FENCE_GATE
        - STONE_PLATE
        - WOOD_PLATE
        - WOODEN_DOOR
        - BEACON
    protectiveAura:
        - CHEST
        - DISPENSER
    lockPair:
        - CHEST
        - WOODEN_DOOR
    lockVertical:
        - WOODEN_DOOR
    canSuck:
        - CHEST
        - DISPENSER
